name: main

on:
  push:
    branches:
      - test-action-361
  pull_request:

jobs:
  self-test-happy-path:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      # uses: priya-kinthali/setup-python@test-toolkit
      uses: actions/setup-python@v6
      with:
            python-version:  '3.11'
            cache: pip
            # cache-dependency-path: ${{ github.action_path }}/requirements.txt
            cache-dependency-path: |             
              demo/subdemo/setup.cfg
              subdirectory/requirements-dev.txt
              requirements.txt 
                
  
    # - name: Check pip version
    #   run: pip --version
    
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt 
    - name: Python Version
      shell: bash
      run: python --version
          # requirements-dev.txt
          # requirements-test.txt
          #          requirements.txt
          #           **/setup.cfg
          # **/requirements.txt
          # **/requirements-dev.txt